name: ros

on:
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  build-install-lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]

    steps:
      - name: Create Catkin Workspace
        run: mkdir ~/catkin_ws/src -p

      - name: Checkout this repo
        uses: actions/checkout@v2
        with:
          path: LilFloSystem

      - name: Checkout AWS ROS TTS - caching version
        uses: actions/checkout@v2
        with:
          repository: mjsobrep/tts-ros1
          path: tts-ros1

      #- name: Checkout WebRTC-ROS - dev version
      #  uses: actions/checkout@v2
      #  with:
      #    repository: RobotWebTools/webrtc_ros
      #    ref: develop
      #    path: webrtc_ros

      - name: Link repos into catkin ws
        run: |
          ln -s "$GITHUB_WORKSPACE/LilFloSystem" "$HOME/catkin_ws/src/"
          ln -s "$GITHUB_WORKSPACE/tts-ros1" "$HOME/catkin_ws/src/"
      #- name: Show where we are
      #  run: |
      #    ls
      #    pwd
      #    sudo apt install tree
      #    tree
      #    tree ~/catkin_ws
      #- name: Prevent all of webrtc dev from building
      #  run: touch ./webrtc_ros/webrtc/CATKIN_IGNORE
      - name: Run Install Script
        run: |
          cd "$HOME/catkin_ws/src/LilFloSystem"
          bash gen_install.sh

      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-pip-pylint
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Setup Pylint
        run: |
          python -m pip install --upgrade pip
          echo "::add-path::/home/runner/.local/bin"
          python -m pip install "pylint<2.0.0"

      - name: Lint with pylint
        run: |
          source ~/catkin_ws/src/LilFloSystem/bash_includes
          cd $GITHUB_WORKSPACE/LilFloSystem
          git ls-files | grep 'py$' | xargs pylint --unsafe-load-any-extension=y --disable=fixme

  catkin-lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
    steps:
      - name: Lint Catkin
        run: |
          pip install python-catkin-lint
          cd $GITHUB_WORKSPACE/LilFloSystem
          catkin_lint . -W2

  python-todos:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
        with:
          path: LilFloSystem

      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-pip-pylint
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Setup Pylint
        run: |
          python -m pip install --upgrade pip
          echo "::add-path::/home/runner/.local/bin"
          python -m pip install "pylint<2.0.0"

      - name: Find TODOs
        run: |
          cd $GITHUB_WORKSPACE/LilFloSystem
          git ls-files | grep 'py$' | xargs pylint --disable=all --enable=fixme
